apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: __NAME__
  namespace: eci-pre
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "50"
        autoscaling.knative.dev/minScale: "1"
        k8s.aliyun.com/eci-use-specs: ecs.c5.8xlarge,ecs.g5.4xlarge,ecs.g6.8xlarge
    spec:
      containerConcurrency: 0
      containers:
      - args:
        - standalone
        command:
        - /home/admin/start.sh
        image: __IMAGE__
        ports:
        - containerPort: 7707
          name: h2c

