apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: __NAME__
  namespace: eci-pre
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "50"
        autoscaling.knative.dev/minScale: "1"
        k8s.aliyun.com/eci-use-specs: ecs.c5.8xlarge,ecs.g5.4xlarge,ecs.g6.8xlarge
    spec:
      containerConcurrency: 0
      containers:
      - args:
        - standalone
        command:
        - /home/admin/start.sh
        env:
        - name: CMDEngine
          value: osscmd --id=__OSSID__ --key=__OSSKEY__
            --host=oss-cn-shanghai.aliyuncs.com --thread_num=10 --check_md5=true downloadtodir
            oss://nls-cloud-cn-shanghai/tts/service/4.9.9 /home/admin/nls-tts/disk/data.4.9.9
        - name: app_engine_dataPath
          value: /home/admin/nls-tts/disk/data.4.9.9
        image: __IMAGE__
        ports:
        - containerPort: 7707
          name: h2c

